name: Build, Test and Release to NuGet

on:
  push:
    branches:
    - main
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0

    - name: Restore dependencies
      run: nuget restore

    - name: Get Build Version
      run: |
        Import-Module .github\workflows\GetBuildVersion.psm1
        $version = GetBuildVersion -VersionString ${{github.event.release.tag_name || ''}}
        echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    - name: Build
      run: dotnet build -c Release${{github.event.release.tag_name && ' -p:Version='}}$BUILD_VERSION

    - name: Test
      run: dotnet test -c Release --no-build

    - name: Pack nugets
      run: dotnet pack -c Release --no-build --output .
      
    - name: Push to NuGet
      if: github.event_name == 'release'
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json